version: '3.8'

services:
  db:
    image: mysql:8.0 # ปรับเป็น SQL 8.0 เพื่อความทันสมัย (หรือใช้5.7 ตามเดิมได้หากต้องการ)
    container_name: mysql_db_820
    # MySQL 8.0 ใช้ plugin ตัวใหม่ จึงต้องใช้คำสั่งเพื่อให้เข้ากับ client รุ่นเก่าได้ดีขึ้น
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8820:3306"
    volumes:
      - mysql_data_820:/var/lib/mysql
    networks:
      - wblab820
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_820
    environment:
      PMA_HOST: db #ใช้ชื่อ Service "db" แทนชื่อ Container เพื่อความยืดหยุ่นในระบบ Network
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M #เพิ่มลิมิตการอัพโหลด SQL
    ports:
      - "8030:80"
    depends_on:
      - db
    networks:
      - wblab820
    restart: always

networks:
  wblab820:
    driver: bridge

volumes:
  mysql_data_820:
    driver: local
